# Generated by Django 3.2 on 2021-04-17 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('office', models.CharField(max_length=120)),
                ('depth', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=150)),
                ('phone', models.CharField(max_length=19)),
            ],
        ),
    ]
