# Generated by Django 3.2 on 2021-04-25 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Controller', '0002_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='id_user',
            field=models.ManyToManyField(to='Controller.User'),
        ),
        migrations.AddField(
            model_name='group',
            name='type',
            field=models.CharField(default=(['1', '8'], 'duo'), max_length=3),
            preserve_default=False,
        ),
    ]
