# Generated by Django 3.2 on 2021-04-25 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Controller', '0003_auto_20210425_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id_connect', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=150)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pk_id_user', to='Controller.user')),
            ],
        ),
    ]
