# Generated by Django 3.2 on 2021-04-25 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Controller', '0004_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pk_id_user', to='Controller.user', unique=True),
        ),
    ]
