# Generated by Django 3.2 on 2021-04-25 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Controller', '0005_alter_connection_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='id_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='pk_id_user', to='Controller.user'),
        ),
    ]
