# Generated by Django 3.2 on 2021-04-25 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Controller', '0006_alter_connection_id_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historic',
            fields=[
                ('id_message', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('link', models.TextField()),
                ('dt_create', models.DateTimeField(auto_now_add=True)),
                ('id_group', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='pk_hist_id_group', to='Controller.group')),
                ('id_user', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='pk_hist_id_user', to='Controller.user')),
            ],
        ),
    ]
