# Generated by Django 3.2 on 2021-04-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Controller', '0007_historic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historic',
            name='id_group',
        ),
        migrations.AddField(
            model_name='historic',
            name='id_group',
            field=models.ManyToManyField(related_name='pk_hist_id_group', to='Controller.Group'),
        ),
        migrations.RemoveField(
            model_name='historic',
            name='id_user',
        ),
        migrations.AddField(
            model_name='historic',
            name='id_user',
            field=models.ManyToManyField(related_name='pk_hist_id_user', to='Controller.User'),
        ),
    ]
