# Generated by Django 3.2 on 2021-04-25 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Controller', '0008_auto_20210425_0428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historic',
            name='id_group',
        ),
        migrations.AddField(
            model_name='historic',
            name='id_group',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.RESTRICT, related_name='pk_hist_id_group', to='Controller.group'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='historic',
            name='id_user',
        ),
        migrations.AddField(
            model_name='historic',
            name='id_user',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.RESTRICT, related_name='pk_hist_id_user', to='Controller.user'),
            preserve_default=False,
        ),
    ]
